version: '3.8'

services:
  training:
    build: .
    volumes:
      - ./outputs:/app/outputs
      - ./config:/app/config
      - ./src:/app/src
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - PYTHONUNBUFFERED=1
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  tensorboard:
    image: tensorflow/tensorflow:latest
    command: tensorboard --logdir /logs --bind_all
    ports:
      - "6006:6006"
    volumes:
      - ./outputs:/logs 