# 训练配置 - 极简测试版本
training:
  num_epochs: 3         
  steps_per_epoch: 16   # 极大减少步数以加快测试
  eval_interval: 1      
  batch_size: 16        # 减小批次大小
  num_processes: 1      # 使用单进程
  max_steps: 1000    
  checkpoint_dir: "outputs/checkpoints"
  tensorboard_dir: "outputs/tensorboard"
  num_workers: 0       # 不使用额外工作线程 
  prefetch_factor: 2   
  pin_memory: false     
  parallel_envs: 1     # 不使用并行环境

# PPO算法配置
ppo:
  learning_rate: 3e-4
  gamma: 0.99
  epsilon: 0.2
  value_coef: 0.5
  entropy_coef: 0.01
  epochs: 3           
  num_updates: 1      
  lambda_: 0.95
  clip_grad_norm: 0.5
  target_kl: 0.01
  mini_batch_size: 8  # 减小mini-batch大小
  num_mini_batches: 2  # 每次更新的mini-batch数量

# 游戏环境配置
environment:
  num_players: 2
  enable_bug_card: false  # 先禁用Bug卡
  three_rounds: false
  max_program_size: 10
  #board_size: 8
  #observation_type: "full"  # 观察空间类型
  #reward_shaping: true     # 是否使用奖励整形

# 模型配置
model:
  input_channels: 9    # 输入通道数

# 设备配置
device: cuda
seed: 42              # 随机种子
cuda_deterministic: false  # 关闭确定性计算以提高速度

# 输出配置
output:
  base_dir: outputs
  save_interval: 1    # 更频繁地保存
  log_level: INFO      # 减少日志输出提高性能
  save_model: true
  save_optimizer: false
  eval_episodes: 5   # 评估时的对局数

# 评估配置
evaluation:
  eval_frequency: 10  # 每10步评估一次
  num_episodes: 2       # 每次评估进行2局游戏
  save_best_only: true  # 只保存最佳模型 

# 性能优化配置
optimization:
  use_torch_compile: false    # 不使用PyTorch编译功能
  memory_efficient: true     # 启用内存效率优化
  gradient_accumulation: 1   # 梯度累积步数
  use_fused_adam: false      # 不使用融合Adam优化器
  use_amp: false             # 不使用自动混合精度
  jit_script: false          # 不使用JIT脚本优化 