# 训练配置 - 极简测试版本
training:
  num_epochs: 20               # 增加到20个epoch
  steps_per_epoch: 32          # 每个epoch执行32步
  eval_interval: 2             # 每2个epoch评估一次
  batch_size: 16               # 批次大小
  num_processes: 1             # 进程数量
  num_workers: 0               # 数据加载器的工作线程数
  prefetch_factor: 2           # 预取因子
  pin_memory: false            # 是否锁定内存
  parallel_envs: 1             # 并行环境数量
  max_steps: 20                # 最大步数
  checkpoint_dir: "outputs/checkpoints"
  tensorboard_dir: "outputs/tensorboard"
  save_interval: 1    # 更频繁地保存
  log_level: INFO      # 减少日志输出提高性能
  save_model: true
  save_optimizer: false
  eval_episodes: 5   # 评估时的对局数

# PPO算法配置
ppo:
  learning_rate: "1e-4"        # 降低学习率提高稳定性
  gamma: 0.99                  # 折扣因子
  epsilon: 0.2                 # PPO裁剪比率
  value_coef: 0.5              # 价值函数损失系数
  entropy_coef: 0.02           # 提高熵损失系数促进探索
  epochs: 5                    # 增加PPO更新轮数
  lambda_: 0.95                # GAE参数
  clip_grad_norm: 0.5
  target_kl: 0.01
  mini_batch_size: 8  # 减小mini-batch大小
  num_mini_batches: 2  # 每次更新的mini-batch数量

# 游戏环境配置
environment:
  num_players: 1               # 玩家数量
  board_size: 8                # 棋盘大小
  max_program_size: 10         # 最大程序大小
  max_steps: 20                # 最大步数
  use_simplified_rules: true   # 使用简化规则
  enable_bug_card: false  # 先禁用Bug卡
  three_rounds: false
  #observation_type: "full"  # 观察空间类型
  #reward_shaping: true     # 是否使用奖励整形

# 模型配置
model:
  input_channels: 9            # 输入通道数量

# 设备配置
device: cuda
seed: 42              # 随机种子
cuda_deterministic: false  # 关闭确定性计算以提高速度

# 输出配置
output:
  base_dir: outputs

# 评估配置
evaluation:
  eval_frequency: 10  # 每10步评估一次
  num_episodes: 2              # 评估局数
  save_best_only: true  # 只保存最佳模型 

# 性能优化配置
optimization:
  use_torch_compile: false    # 不使用PyTorch编译功能
  memory_efficient: true     # 启用内存效率优化
  gradient_accumulation: 1   # 梯度累积步数
  use_fused_adam: false      # 不使用融合Adam优化器
  use_amp: false             # 不使用自动混合精度
  jit_script: false          # 不使用JIT脚本优化 